/*! Video.js v4.1.0 Copyright 2013 Brightcove, Inc. https://github.com/videojs/video.js/blob/master/LICENSE */ (function() {var b=void 0,f=!0,j=null,l=!1;function m(){return function(){}}function p(a){return function(){return this[a]}}function s(a){return function(){return a}}var t;document.createElement("video");document.createElement("audio");document.createElement("track");function u(a,c,d){if("string"===typeof a){0===a.indexOf("#")&&(a=a.slice(1));if(u.wa[a])return u.wa[a];a=u.u(a)}if(!a||!a.nodeName)throw new TypeError("The element or ID supplied is not valid. (videojs)");return a.player||new u.w(a,c,d)}var v=u;
window.Fd=window.Gd=u;u.Sb="4.1";u.yc="https:"==document.location.protocol?"https://":"http://";u.options={techOrder:["html5","flash"],html5:{},flash:{},width:300,height:150,defaultVolume:0,children:{mediaLoader:{},posterImage:{},textTrackDisplay:{},loadingSpinner:{},bigPlayButton:{},controlBar:{}}};"GENERATED_CDN_VSN"!==u.Sb&&(v.options.flash.swf=u.yc+"vjs.zencdn.net/"+u.Sb+"/video-js.swf");u.wa={};u.ka=u.CoreObject=m();
u.ka.extend=function(a){var c,d;a=a||{};c=a.init||a.h||this.prototype.init||this.prototype.h||m();d=function(){c.apply(this,arguments)};d.prototype=u.j.create(this.prototype);d.prototype.constructor=d;d.extend=u.ka.extend;d.create=u.ka.create;for(var e in a)a.hasOwnProperty(e)&&(d.prototype[e]=a[e]);return d};u.ka.create=function(){var a=u.j.create(this.prototype);this.apply(a,arguments);return a};
u.c=function(a,c,d){var e=u.getData(a);e.z||(e.z={});e.z[c]||(e.z[c]=[]);d.s||(d.s=u.s++);e.z[c].push(d);e.W||(e.disabled=l,e.W=function(c){if(!e.disabled){c=u.hc(c);var d=e.z[c.type];if(d)for(var d=d.slice(0),k=0,q=d.length;k<q&&!c.nc();k++)d[k].call(a,c)}});1==e.z[c].length&&(document.addEventListener?a.addEventListener(c,e.W,l):document.attachEvent&&a.attachEvent("on"+c,e.W))};
u.l=function(a,c,d){if(u.mc(a)){var e=u.getData(a);if(e.z)if(c){var g=e.z[c];if(g){if(d){if(d.s)for(e=0;e<g.length;e++)g[e].s===d.s&&g.splice(e--,1)}else e.z[c]=[];u.ec(a,c)}}else for(g in e.z)c=g,e.z[c]=[],u.ec(a,c)}};u.ec=function(a,c){var d=u.getData(a);0===d.z[c].length&&(delete d.z[c],document.removeEventListener?a.removeEventListener(c,d.W,l):document.detachEvent&&a.detachEvent("on"+c,d.W));u.Ab(d.z)&&(delete d.z,delete d.W,delete d.disabled);u.Ab(d)&&u.rc(a)};
u.hc=function(a){function c(){return f}function d(){return l}if(!a||!a.Bb){var e=a||window.event;a={};for(var g in e)"layerX"!==g&&"layerY"!==g&&(a[g]=e[g]);a.target||(a.target=a.srcElement||document);a.relatedTarget=a.fromElement===a.target?a.toElement:a.fromElement;a.preventDefault=function(){e.preventDefault&&e.preventDefault();a.returnValue=l;a.zb=c};a.zb=d;a.stopPropagation=function(){e.stopPropagation&&e.stopPropagation();a.cancelBubble=f;a.Bb=c};a.Bb=d;a.stopImmediatePropagation=function(){e.stopImmediatePropagation&&
e.stopImmediatePropagation();a.nc=c;a.stopPropagation()};a.nc=d;if(a.clientX!=j){g=document.documentElement;var h=document.body;a.pageX=a.clientX+(g&&g.scrollLeft||h&&h.scrollLeft||0)-(g&&g.clientLeft||h&&h.clientLeft||0);a.pageY=a.clientY+(g&&g.scrollTop||h&&h.scrollTop||0)-(g&&g.clientTop||h&&h.clientTop||0)}a.which=a.charCode||a.keyCode;a.button!=j&&(a.button=a.button&1?0:a.button&4?1:a.button&2?2:0)}return a};
u.i=function(a,c){var d=u.mc(a)?u.getData(a):{},e=a.parentNode||a.ownerDocument;"string"===typeof c&&(c={type:c,target:a});c=u.hc(c);d.W&&d.W.call(a,c);if(e&&!c.Bb()&&c.bubbles!==l)u.i(e,c);else if(!e&&!c.zb()&&(d=u.getData(c.target),c.target[c.type])){d.disabled=f;if("function"===typeof c.target[c.type])c.target[c.type]();d.disabled=l}return!c.zb()};u.U=function(a,c,d){function e(){u.l(a,c,e);d.apply(this,arguments)}e.s=d.s=d.s||u.s++;u.c(a,c,e)};var w=Object.prototype.hasOwnProperty;
u.e=function(a,c){var d=document.createElement(a||"div"),e;for(e in c)w.call(c,e)&&(-1!==e.indexOf("aria-")||"role"==e?d.setAttribute(e,c[e]):d[e]=c[e]);return d};u.aa=function(a){return a.charAt(0).toUpperCase()+a.slice(1)};u.j={};u.j.create=Object.create||function(a){function c(){}c.prototype=a;return new c};u.j.ta=function(a,c,d){for(var e in a)w.call(a,e)&&c.call(d||this,e,a[e])};u.j.B=function(a,c){if(!c)return a;for(var d in c)w.call(c,d)&&(a[d]=c[d]);return a};
u.j.gc=function(a,c){var d,e,g;a=u.j.copy(a);for(d in c)w.call(c,d)&&(e=a[d],g=c[d],a[d]=u.j.oc(e)&&u.j.oc(g)?u.j.gc(e,g):c[d]);return a};u.j.copy=function(a){return u.j.B({},a)};u.j.oc=function(a){return!!a&&"object"===typeof a&&"[object Object]"===a.toString()&&a.constructor===Object};u.bind=function(a,c,d){function e(){return c.apply(a,arguments)}c.s||(c.s=u.s++);e.s=d?d+"_"+c.s:c.s;return e};u.qa={};u.s=1;u.expando="vdata"+(new Date).getTime();
u.getData=function(a){var c=a[u.expando];c||(c=a[u.expando]=u.s++,u.qa[c]={});return u.qa[c]};u.mc=function(a){a=a[u.expando];return!(!a||u.Ab(u.qa[a]))};u.rc=function(a){var c=a[u.expando];if(c){delete u.qa[c];try{delete a[u.expando]}catch(d){a.removeAttribute?a.removeAttribute(u.expando):a[u.expando]=j}}};u.Ab=function(a){for(var c in a)if(a[c]!==j)return l;return f};u.o=function(a,c){-1==(" "+a.className+" ").indexOf(" "+c+" ")&&(a.className=""===a.className?c:a.className+" "+c)};
u.t=function(a,c){if(-1!=a.className.indexOf(c)){for(var d=a.className.split(" "),e=d.length-1;0<=e;e--)d[e]===c&&d.splice(e,1);a.className=d.join(" ")}};u.ma=u.e("video");u.G=navigator.userAgent;u.Ec=/iPhone/i.test(u.G);u.Dc=/iPad/i.test(u.G);u.Fc=/iPod/i.test(u.G);u.Cc=u.Ec||u.Dc||u.Fc;var aa=u,x;var y=u.G.match(/OS (\d+)_/i);x=y&&y[1]?y[1]:b;aa.xd=x;u.Ac=/Android/i.test(u.G);var ba=u,z;var A=u.G.match(/Android (\d+)(?:\.(\d+))?(?:\.(\d+))*/i),B,C;
A?(B=A[1]&&parseFloat(A[1]),C=A[2]&&parseFloat(A[2]),z=B&&C?parseFloat(A[1]+"."+A[2]):B?B:j):z=j;ba.zc=z;u.Gc=u.Ac&&/webkit/i.test(u.G)&&2.3>u.zc;u.Bc=/Firefox/i.test(u.G);u.yd=/Chrome/i.test(u.G);u.Ic="ontouchstart"in window;u.wb=function(a){var c={};if(a&&a.attributes&&0<a.attributes.length)for(var d=a.attributes,e,g,h=d.length-1;0<=h;h--){e=d[h].name;g=d[h].value;if("boolean"===typeof a[e]||-1!==",autoplay,controls,loop,muted,default,".indexOf(","+e+","))g=g!==j?f:l;c[e]=g}return c};
u.Bd=function(a,c){var d="";document.defaultView&&document.defaultView.getComputedStyle?d=document.defaultView.getComputedStyle(a,"").getPropertyValue(c):a.currentStyle&&(d=a["client"+c.substr(0,1).toUpperCase()+c.substr(1)]+"px");return d};u.yb=function(a,c){c.firstChild?c.insertBefore(a,c.firstChild):c.appendChild(a)};u.Nb={};u.u=function(a){0===a.indexOf("#")&&(a=a.slice(1));return document.getElementById(a)};
u.La=function(a,c){c=c||a;var d=Math.floor(a%60),e=Math.floor(a/60%60),g=Math.floor(a/3600),h=Math.floor(c/60%60),k=Math.floor(c/3600),g=0<g||0<k?g+":":"";return g+(((g||10<=h)&&10>e?"0"+e:e)+":")+(10>d?"0"+d:d)};u.Lc=function(){document.body.focus();document.onselectstart=s(l)};u.sd=function(){document.onselectstart=s(f)};u.trim=function(a){return a.toString().replace(/^\s+/,"").replace(/\s+$/,"")};u.round=function(a,c){c||(c=0);return Math.round(a*Math.pow(10,c))/Math.pow(10,c)};
u.sb=function(a,c){return{length:1,start:function(){return a},end:function(){return c}}};
u.get=function(a,c,d){var e=0===a.indexOf("file:")||0===window.location.href.indexOf("file:")&&-1===a.indexOf("http");"undefined"===typeof XMLHttpRequest&&(window.XMLHttpRequest=function(){try{return new window.ActiveXObject("Msxml2.XMLHTTP.6.0")}catch(a){}try{return new window.ActiveXObject("Msxml2.XMLHTTP.3.0")}catch(c){}try{return new window.ActiveXObject("Msxml2.XMLHTTP")}catch(d){}throw Error("This browser does not support XMLHttpRequest.");});var g=new XMLHttpRequest;try{g.open("GET",a)}catch(h){d(h)}g.onreadystatechange=
function(){4===g.readyState&&(200===g.status||e&&0===g.status?c(g.responseText):d&&d())};try{g.send()}catch(k){d&&d(k)}};u.ld=function(a){try{var c=window.localStorage||l;c&&(c.volume=a)}catch(d){22==d.code||1014==d.code?u.log("LocalStorage Full (VideoJS)",d):18==d.code?u.log("LocalStorage not allowed (VideoJS)",d):u.log("LocalStorage Error (VideoJS)",d)}};u.kc=function(a){a.match(/^https?:\/\//)||(a=u.e("div",{innerHTML:'<a href="'+a+'">x</a>'}).firstChild.href);return a};
u.log=function(){u.log.history=u.log.history||[];u.log.history.push(arguments);window.console&&window.console.log(Array.prototype.slice.call(arguments))};u.Tc=function(a){var c,d;a.getBoundingClientRect&&a.parentNode&&(c=a.getBoundingClientRect());if(!c)return{left:0,top:0};a=document.documentElement;d=document.body;return{left:c.left+(window.pageXOffset||d.scrollLeft)-(a.clientLeft||d.clientLeft||0),top:c.top+(window.pageYOffset||d.scrollTop)-(a.clientTop||d.clientTop||0)}};
u.d=u.ka.extend({h:function(a,c,d){this.b=a;this.f=u.j.copy(this.f);c=this.options(c);this.Q=c.id||(c.el&&c.el.id?c.el.id:a.id()+"_component_"+u.s++);this.Yc=c.name||j;this.a=c.el||this.e();this.H=[];this.qb={};this.V={};if((a=this.f)&&a.children){var e=this;u.j.ta(a.children,function(a,c){c!==l&&!c.loadEvent&&(e[a]=e.$(a,c))})}this.M(d)}});t=u.d.prototype;
t.D=function(){this.i("dispose");if(this.H)for(var a=this.H.length-1;0<=a;a--)this.H[a].D&&this.H[a].D();this.V=this.qb=this.H=j;this.l();this.a.parentNode&&this.a.parentNode.removeChild(this.a);u.rc(this.a);this.a=j};t.L=p("b");t.options=function(a){return a===b?this.f:this.f=u.j.gc(this.f,a)};t.e=function(a,c){return u.e(a,c)};t.u=p("a");t.id=p("Q");t.name=p("Yc");t.children=p("H");
t.$=function(a,c){var d,e;"string"===typeof a?(e=a,c=c||{},d=c.componentClass||u.aa(e),c.name=e,d=new window.videojs[d](this.b||this,c)):d=a;this.H.push(d);"function"===typeof d.id&&(this.qb[d.id()]=d);(e=e||d.name&&d.name())&&(this.V[e]=d);"function"===typeof d.el&&d.el()&&(this.ra||this.a).appendChild(d.el());return d};
t.removeChild=function(a){"string"===typeof a&&(a=this.V[a]);if(a&&this.H){for(var c=l,d=this.H.length-1;0<=d;d--)if(this.H[d]===a){c=f;this.H.splice(d,1);break}c&&(this.qb[a.id]=j,this.V[a.name]=j,(c=a.u())&&c.parentNode===(this.ra||this.a)&&(this.ra||this.a).removeChild(a.u()))}};t.T=s("");t.c=function(a,c){u.c(this.a,a,u.bind(this,c));return this};t.l=function(a,c){u.l(this.a,a,c);return this};t.U=function(a,c){u.U(this.a,a,u.bind(this,c));return this};t.i=function(a,c){u.i(this.a,a,c);return this};
t.M=function(a){a&&(this.ba?a.call(this):(this.Sa===b&&(this.Sa=[]),this.Sa.push(a)));return this};t.Ua=function(){this.ba=f;var a=this.Sa;if(a&&0<a.length){for(var c=0,d=a.length;c<d;c++)a[c].call(this);this.Sa=[];this.i("ready")}};t.o=function(a){u.o(this.a,a);return this};t.t=function(a){u.t(this.a,a);return this};t.show=function(){this.a.style.display="block";return this};t.C=function(){this.a.style.display="none";return this};function D(a){a.t("vjs-lock-showing")}
t.disable=function(){this.C();this.show=m()};t.width=function(a,c){return E(this,"width",a,c)};t.height=function(a,c){return E(this,"height",a,c)};t.Pc=function(a,c){return this.width(a,f).height(c)};function E(a,c,d,e){if(d!==b)return a.a.style[c]=-1!==(""+d).indexOf("%")||-1!==(""+d).indexOf("px")?d:"auto"===d?"":d+"px",e||a.i("resize"),a;if(!a.a)return 0;d=a.a.style[c];e=d.indexOf("px");return-1!==e?parseInt(d.slice(0,e),10):parseInt(a.a["offset"+u.aa(c)],10)}
u.q=u.d.extend({h:function(a,c){u.d.call(this,a,c);var d=l;this.c("touchstart",function(a){a.preventDefault();d=f});this.c("touchmove",function(){d=l});var e=this;this.c("touchend",function(a){d&&e.p(a);a.preventDefault()});this.c("click",this.p);this.c("focus",this.Oa);this.c("blur",this.Na)}});t=u.q.prototype;
t.e=function(a,c){c=u.j.B({className:this.T(),innerHTML:'<div class="vjs-control-content"><span class="vjs-control-text">'+(this.pa||"Need Text")+"</span></div>",hd:"button","aria-live":"polite",tabIndex:0},c);return u.d.prototype.e.call(this,a,c)};t.T=function(){return"vjs-control "+u.d.prototype.T.call(this)};t.p=m();t.Oa=function(){u.c(document,"keyup",u.bind(this,this.ca))};t.ca=function(a){if(32==a.which||13==a.which)a.preventDefault(),this.p()};
t.Na=function(){u.l(document,"keyup",u.bind(this,this.ca))};u.O=u.d.extend({h:function(a,c){u.d.call(this,a,c);this.Kc=this.V[this.f.barName];this.handle=this.V[this.f.handleName];a.c(this.pc,u.bind(this,this.update));this.c("mousedown",this.Pa);this.c("touchstart",this.Pa);this.c("focus",this.Oa);this.c("blur",this.Na);this.c("click",this.p);this.b.c("controlsvisible",u.bind(this,this.update));a.M(u.bind(this,this.update));this.P={}}});t=u.O.prototype;
t.e=function(a,c){c=c||{};c.className+=" vjs-slider";c=u.j.B({hd:"slider","aria-valuenow":0,"aria-valuemin":0,"aria-valuemax":100,tabIndex:0},c);return u.d.prototype.e.call(this,a,c)};t.Pa=function(a){a.preventDefault();u.Lc();this.P.move=u.bind(this,this.Gb);this.P.end=u.bind(this,this.Hb);u.c(document,"mousemove",this.P.move);u.c(document,"mouseup",this.P.end);u.c(document,"touchmove",this.P.move);u.c(document,"touchend",this.P.end);this.Gb(a)};
t.Hb=function(){u.sd();u.l(document,"mousemove",this.P.move,l);u.l(document,"mouseup",this.P.end,l);u.l(document,"touchmove",this.P.move,l);u.l(document,"touchend",this.P.end,l);this.update()};t.update=function(){if(this.a){var a,c=this.xb(),d=this.handle,e=this.Kc;isNaN(c)&&(c=0);a=c;if(d){a=this.a.offsetWidth;var g=d.u().offsetWidth;a=g?g/a:0;c*=1-a;a=c+a/2;d.u().style.left=u.round(100*c,2)+"%"}e.u().style.width=u.round(100*a,2)+"%"}};
function F(a,c){var d,e,g,h;d=a.a;e=u.Tc(d);h=g=d.offsetWidth;d=a.handle;if(a.f.td)return h=e.top,e=c.changedTouches?c.changedTouches[0].pageY:c.pageY,d&&(d=d.u().offsetHeight,h+=d/2,g-=d),Math.max(0,Math.min(1,(h-e+g)/g));g=e.left;e=c.changedTouches?c.changedTouches[0].pageX:c.pageX;d&&(d=d.u().offsetWidth,g+=d/2,h-=d);return Math.max(0,Math.min(1,(e-g)/h))}t.Oa=function(){u.c(document,"keyup",u.bind(this,this.ca))};
t.ca=function(a){37==a.which?(a.preventDefault(),this.vc()):39==a.which&&(a.preventDefault(),this.wc())};t.Na=function(){u.l(document,"keyup",u.bind(this,this.ca))};t.p=function(a){a.stopImmediatePropagation();a.preventDefault()};u.fa=u.d.extend();u.fa.prototype.defaultValue=0;u.fa.prototype.e=function(a,c){c=c||{};c.className+=" vjs-slider-handle";c=u.j.B({innerHTML:'<span class="vjs-control-text">'+this.defaultValue+"</span>"},c);return u.d.prototype.e.call(this,"div",c)};u.la=u.d.extend();
function ca(a,c){a.$(c);c.c("click",u.bind(a,function(){D(this)}))}u.la.prototype.e=function(){var a=this.options().Nc||"ul";this.ra=u.e(a,{className:"vjs-menu-content"});a=u.d.prototype.e.call(this,"div",{append:this.ra,className:"vjs-menu"});a.appendChild(this.ra);u.c(a,"click",function(a){a.preventDefault();a.stopImmediatePropagation()});return a};u.N=u.q.extend({h:function(a,c){u.q.call(this,a,c);this.selected(c.selected)}});
u.N.prototype.e=function(a,c){return u.q.prototype.e.call(this,"li",u.j.B({className:"vjs-menu-item",innerHTML:this.f.label},c))};u.N.prototype.p=function(){this.selected(f)};u.N.prototype.selected=function(a){a?(this.o("vjs-selected"),this.a.setAttribute("aria-selected",f)):(this.t("vjs-selected"),this.a.setAttribute("aria-selected",l))};
u.R=u.q.extend({h:function(a,c){u.q.call(this,a,c);this.va=this.Ka();this.$(this.va);this.J&&0===this.J.length&&this.C();this.c("keyup",this.ca);this.a.setAttribute("aria-haspopup",f);this.a.setAttribute("role","button")}});t=u.R.prototype;t.oa=l;t.Ka=function(){var a=new u.la(this.b);this.options().title&&a.u().appendChild(u.e("li",{className:"vjs-menu-title",innerHTML:u.aa(this.A),qd:-1}));if(this.J=this.createItems())for(var c=0;c<this.J.length;c++)ca(a,this.J[c]);return a};t.sa=m();
t.T=function(){return this.className+" vjs-menu-button "+u.q.prototype.T.call(this)};t.Oa=m();t.Na=m();t.p=function(){this.U("mouseout",u.bind(this,function(){D(this.va);this.a.blur()}));this.oa?G(this):H(this)};t.ca=function(a){a.preventDefault();32==a.which||13==a.which?this.oa?G(this):H(this):27==a.which&&this.oa&&G(this)};function H(a){a.oa=f;a.va.o("vjs-lock-showing");a.a.setAttribute("aria-pressed",f);a.J&&0<a.J.length&&a.J[0].u().focus()}
function G(a){a.oa=l;D(a.va);a.a.setAttribute("aria-pressed",l)}
u.w=u.d.extend({h:function(a,c,d){this.F=a;c=u.j.B(da(a),c);this.v={};this.qc=c.poster;this.rb=c.controls;a.controls=l;u.d.call(this,this,c,d);this.controls()?this.o("vjs-controls-enabled"):this.o("vjs-controls-disabled");this.U("play",function(a){u.i(this.a,{type:"firstplay",target:this.a})||(a.preventDefault(),a.stopPropagation(),a.stopImmediatePropagation())});this.c("ended",this.$c);this.c("play",this.Jb);this.c("firstplay",this.ad);this.c("pause",this.Ib);this.c("progress",this.cd);this.c("durationchange",
this.Zc);this.c("error",this.Fb);this.c("fullscreenchange",this.bd);u.wa[this.Q]=this;c.plugins&&u.j.ta(c.plugins,function(a,c){this[a](c)},this);var e,g,h,k;e=this.sc;a=function(){e();clearInterval(g);g=setInterval(u.bind(this,e),250)};c=function(){e();clearInterval(g)};this.c("mousedown",a);this.c("mousemove",e);this.c("mouseup",c);this.c("keydown",e);this.c("keyup",e);this.c("touchstart",a);this.c("touchmove",e);this.c("touchend",c);this.c("touchcancel",c);h=setInterval(u.bind(this,function(){this.ja&&
(this.ja=l,I(this,f),clearTimeout(k),k=setTimeout(u.bind(this,function(){this.ja||I(this,l)}),2E3))}),250);this.c("dispose",function(){clearInterval(h);clearTimeout(k)})}});t=u.w.prototype;t.f=u.options;t.D=function(){this.i("dispose");this.l("dispose");u.wa[this.Q]=j;this.F&&this.F.player&&(this.F.player=j);this.a&&this.a.player&&(this.a.player=j);clearInterval(this.Ra);this.ya();this.g&&this.g.D();u.d.prototype.D.call(this)};
function da(a){var c={sources:[],tracks:[]};u.j.B(c,u.wb(a));if(a.hasChildNodes()){var d,e,g,h;a=a.childNodes;g=0;for(h=a.length;g<h;g++)d=a[g],e=d.nodeName.toLowerCase(),"source"===e?c.sources.push(u.wb(d)):"track"===e&&c.tracks.push(u.wb(d))}return c}
t.e=function(){var a=this.a=u.d.prototype.e.call(this,"div"),c=this.F;c.removeAttribute("width");c.removeAttribute("height");if(c.hasChildNodes()){var d,e,g,h,k;d=c.childNodes;e=d.length;for(k=[];e--;)g=d[e],h=g.nodeName.toLowerCase(),("source"===h||"track"===h)&&k.push(g);for(d=0;d<k.length;d++)c.removeChild(k[d])}c.id=c.id||"vjs_video_"+u.s++;a.id=c.id;a.className=c.className;c.id+="_html5_api";c.className="vjs-tech";c.player=a.player=this;this.o("vjs-paused");this.width(this.f.width,f);this.height(this.f.height,
f);c.parentNode&&c.parentNode.insertBefore(a,c);u.yb(c,a);return a};
function J(a,c,d){a.g?(a.ba=l,a.g.D(),a.Db&&(a.Db=l,clearInterval(a.Ra)),a.Eb&&K(a),a.g=l):"Html5"!==c&&a.F&&(a.a.removeChild(a.F),a.F.player=j,a.F=j);a.za=c;a.ba=l;var e=u.j.B({source:d,parentEl:a.a},a.f[c.toLowerCase()]);d&&(d.src==a.v.src&&0<a.v.currentTime&&(e.startTime=a.v.currentTime),a.v.src=d.src);a.g=new window.videojs[c](a,e);a.g.M(function(){this.b.Ua();if(!this.k.Lb){var a=this.b;a.Db=f;a.Ra=setInterval(u.bind(a,function(){this.v.lb<this.buffered().end(0)?this.i("progress"):1==this.Ja()&&
(clearInterval(this.Ra),this.i("progress"))}),500);a.g.U("progress",function(){this.k.Lb=f;var a=this.b;a.Db=l;clearInterval(a.Ra)})}this.k.Ob||(a=this.b,a.Eb=f,a.c("play",a.xc),a.c("pause",a.ya),a.g.U("timeupdate",function(){this.k.Ob=f;K(this.b)}))})}function K(a){a.Eb=l;a.ya();a.l("play",a.xc);a.l("pause",a.ya)}t.xc=function(){this.fc&&this.ya();this.fc=setInterval(u.bind(this,function(){this.i("timeupdate")}),250)};t.ya=function(){clearInterval(this.fc)};
t.$c=function(){this.f.loop&&(this.currentTime(0),this.play())};t.Jb=function(){u.t(this.a,"vjs-paused");u.o(this.a,"vjs-playing")};t.ad=function(){this.f.starttime&&this.currentTime(this.f.starttime);this.o("vjs-has-started")};t.Ib=function(){u.t(this.a,"vjs-playing");u.o(this.a,"vjs-paused")};t.cd=function(){1==this.Ja()&&this.i("loadedalldata")};t.Zc=function(){this.duration(L(this,"duration"))};t.Fb=function(a){u.log("Video Error",a)};t.bd=function(){this.I?this.o("vjs-fullscreen"):this.t("vjs-fullscreen")};
function M(a,c,d){if(a.g&&!a.g.ba)a.g.M(function(){this[c](d)});else try{a.g[c](d)}catch(e){throw u.log(e),e;}}function L(a,c){if(a.g.ba)try{return a.g[c]()}catch(d){throw a.g[c]===b?u.log("Video.js: "+c+" method not defined for "+a.za+" playback technology.",d):"TypeError"==d.name?(u.log("Video.js: "+c+" unavailable on "+a.za+" playback technology element.",d),a.g.ba=l):u.log(d),d;}}t.play=function(){M(this,"play");return this};t.pause=function(){M(this,"pause");return this};
t.paused=function(){return L(this,"paused")===l?l:f};t.currentTime=function(a){return a!==b?(this.v.Dd=a,M(this,"setCurrentTime",a),this.Eb&&this.i("timeupdate"),this):this.v.currentTime=L(this,"currentTime")||0};t.duration=function(a){return a!==b?(this.v.duration=parseFloat(a),this):this.v.duration};t.buffered=function(){var a=L(this,"buffered"),c=a.length-1,d=this.v.lb=this.v.lb||0;a&&(0<=c&&a.end(c)!==d)&&(d=a.end(c),this.v.lb=d);return u.sb(0,d)};
t.Ja=function(){return this.duration()?this.buffered().end(0)/this.duration():0};t.volume=function(a){if(a!==b)return a=Math.max(0,Math.min(1,parseFloat(a))),this.v.volume=a,M(this,"setVolume",a),u.ld(a),this;a=parseFloat(L(this,"volume"));return isNaN(a)?1:a};t.muted=function(a){return a!==b?(M(this,"setMuted",a),this):L(this,"muted")||l};t.Ta=function(){return L(this,"supportsFullScreen")||l};
t.xa=function(){var a=u.Nb.xa;this.I=f;a?(u.c(document,a.ub,u.bind(this,function(c){this.I=document[a.I];this.I===l&&u.l(document,a.ub,arguments.callee);this.i("fullscreenchange")})),this.a[a.tc]()):this.g.Ta()?M(this,"enterFullScreen"):(this.Vc=f,this.Qc=document.documentElement.style.overflow,u.c(document,"keydown",u.bind(this,this.ic)),document.documentElement.style.overflow="hidden",u.o(document.body,"vjs-full-window"),this.i("enterFullWindow"),this.i("fullscreenchange"));return this};
t.ob=function(){var a=u.Nb.xa;this.I=l;if(a)document[a.nb]();else this.g.Ta()?M(this,"exitFullScreen"):(N(this),this.i("fullscreenchange"));return this};t.ic=function(a){27===a.keyCode&&(this.I===f?this.ob():N(this))};function N(a){a.Vc=l;u.l(document,"keydown",a.ic);document.documentElement.style.overflow=a.Qc;u.t(document.body,"vjs-full-window");a.i("exitFullWindow")}
t.src=function(a){if(a instanceof Array){var c;a:{c=a;for(var d=0,e=this.f.techOrder;d<e.length;d++){var g=u.aa(e[d]),h=window.videojs[g];if(h.isSupported())for(var k=0,q=c;k<q.length;k++){var n=q[k];if(h.canPlaySource(n)){c={source:n,g:g};break a}}}c=l}c?(a=c.source,c=c.g,c==this.za?this.src(a):J(this,c,a)):this.a.appendChild(u.e("p",{innerHTML:'Sorry, no compatible source and playback technology were found for this video. Try using another browser like <a href="http://bit.ly/ccMUEC">Chrome</a> or download the latest <a href="http://adobe.ly/mwfN1">Adobe Flash Player</a>.'}))}else a instanceof
Object?window.videojs[this.za].canPlaySource(a)?this.src(a.src):this.src([a]):(this.v.src=a,this.ba?(M(this,"src",a),"auto"==this.f.preload&&this.load(),this.f.autoplay&&this.play()):this.M(function(){this.src(a)}));return this};t.load=function(){M(this,"load");return this};t.currentSrc=function(){return L(this,"currentSrc")||this.v.src||""};t.Qa=function(a){return a!==b?(M(this,"setPreload",a),this.f.preload=a,this):L(this,"preload")};
t.autoplay=function(a){return a!==b?(M(this,"setAutoplay",a),this.f.autoplay=a,this):L(this,"autoplay")};t.loop=function(a){return a!==b?(M(this,"setLoop",a),this.f.loop=a,this):L(this,"loop")};t.poster=function(a){a!==b&&(this.qc=a);return this.qc};
t.controls=function(a){return a!==b?(a=!!a,this.rb!==a&&((this.rb=a)?(this.t("vjs-controls-disabled"),this.o("vjs-controls-enabled"),this.i("controlsenabled")):(this.t("vjs-controls-enabled"),this.o("vjs-controls-disabled"),this.i("controlsdisabled"))),this):this.rb};u.w.prototype.Rb;t=u.w.prototype;
t.Qb=function(a){return a!==b?(a=!!a,this.Rb!==a&&((this.Rb=a)?(this.o("vjs-using-native-controls"),this.i("usingnativecontrols")):(this.t("vjs-using-native-controls"),this.i("usingcustomcontrols"))),this):this.Rb};t.error=function(){return L(this,"error")};t.ja=f;t.sc=function(){this.ja=f};t.Pb=f;
function I(a,c){return c!==b?(c=!!c,c!==a.Pb&&((a.Pb=c)?(a.ja=f,a.t("vjs-user-inactive"),a.o("vjs-user-active"),a.i("useractive")):(a.ja=l,a.g.U("mousemove",function(a){a.stopPropagation();a.preventDefault()}),a.t("vjs-user-active"),a.o("vjs-user-inactive"),a.i("userinactive"))),a):a.Pb}var O,P,Q;Q=document.createElement("div");P={};
Q.zd!==b?(P.tc="requestFullscreen",P.nb="exitFullscreen",P.ub="fullscreenchange",P.I="fullScreen"):(document.mozCancelFullScreen?(O="moz",P.I=O+"FullScreen"):(O="webkit",P.I=O+"IsFullScreen"),Q[O+"RequestFullScreen"]&&(P.tc=O+"RequestFullScreen",P.nb=O+"CancelFullScreen"),P.ub=O+"fullscreenchange");document[P.nb]&&(u.Nb.xa=P);u.Fa=u.d.extend();
u.Fa.prototype.f={Ed:"play",children:{playToggle:{},currentTimeDisplay:{},timeDivider:{},durationDisplay:{},remainingTimeDisplay:{},progressControl:{},fullscreenToggle:{},volumeControl:{},muteToggle:{}}};u.Fa.prototype.e=function(){return u.e("div",{className:"vjs-control-bar"})};u.Xb=u.q.extend({h:function(a,c){u.q.call(this,a,c);a.c("play",u.bind(this,this.Jb));a.c("pause",u.bind(this,this.Ib))}});t=u.Xb.prototype;t.pa="Play";t.T=function(){return"vjs-play-control "+u.q.prototype.T.call(this)};
t.p=function(){this.b.paused()?this.b.play():this.b.pause()};t.Jb=function(){u.t(this.a,"vjs-paused");u.o(this.a,"vjs-playing");this.a.children[0].children[0].innerHTML="Pause"};t.Ib=function(){u.t(this.a,"vjs-playing");u.o(this.a,"vjs-paused");this.a.children[0].children[0].innerHTML="Play"};u.Ya=u.d.extend({h:function(a,c){u.d.call(this,a,c);a.c("timeupdate",u.bind(this,this.Ca))}});
u.Ya.prototype.e=function(){var a=u.d.prototype.e.call(this,"div",{className:"vjs-current-time vjs-time-controls vjs-control"});this.content=u.e("div",{className:"vjs-current-time-display",innerHTML:'<span class="vjs-control-text">Current Time </span>0:00',"aria-live":"off"});a.appendChild(u.e("div").appendChild(this.content));return a};
u.Ya.prototype.Ca=function(){var a=this.b.Mb?this.b.v.currentTime:this.b.currentTime();this.content.innerHTML='<span class="vjs-control-text">Current Time </span>'+u.La(a,this.b.duration())};u.Za=u.d.extend({h:function(a,c){u.d.call(this,a,c);a.c("timeupdate",u.bind(this,this.Ca))}});
u.Za.prototype.e=function(){var a=u.d.prototype.e.call(this,"div",{className:"vjs-duration vjs-time-controls vjs-control"});this.content=u.e("div",{className:"vjs-duration-display",innerHTML:'<span class="vjs-control-text">Duration Time </span>0:00',"aria-live":"off"});a.appendChild(u.e("div").appendChild(this.content));return a};u.Za.prototype.Ca=function(){this.b.duration()&&(this.content.innerHTML='<span class="vjs-control-text">Duration Time </span>'+u.La(this.b.duration()))};
u.ac=u.d.extend({h:function(a,c){u.d.call(this,a,c)}});u.ac.prototype.e=function(){return u.d.prototype.e.call(this,"div",{className:"vjs-time-divider",innerHTML:"<div><span>/</span></div>"})};u.fb=u.d.extend({h:function(a,c){u.d.call(this,a,c);a.c("timeupdate",u.bind(this,this.Ca))}});
u.fb.prototype.e=function(){var a=u.d.prototype.e.call(this,"div",{className:"vjs-remaining-time vjs-time-controls vjs-control"});this.content=u.e("div",{className:"vjs-remaining-time-display",innerHTML:'<span class="vjs-control-text">Remaining Time </span>-0:00',"aria-live":"off"});a.appendChild(u.e("div").appendChild(this.content));return a};
u.fb.prototype.Ca=function(){this.b.duration()&&this.b.duration()&&(this.content.innerHTML='<span class="vjs-control-text">Remaining Time </span>-'+u.La(this.b.duration()-this.b.currentTime()))};u.Ga=u.q.extend({h:function(a,c){u.q.call(this,a,c)}});u.Ga.prototype.pa="Fullscreen";u.Ga.prototype.T=function(){return"vjs-fullscreen-control "+u.q.prototype.T.call(this)};
u.Ga.prototype.p=function(){this.b.I?(this.b.ob(),this.a.children[0].children[0].innerHTML="Fullscreen"):(this.b.xa(),this.a.children[0].children[0].innerHTML="Non-Fullscreen")};u.eb=u.d.extend({h:function(a,c){u.d.call(this,a,c)}});u.eb.prototype.f={children:{seekBar:{}}};u.eb.prototype.e=function(){return u.d.prototype.e.call(this,"div",{className:"vjs-progress-control vjs-control"})};u.Yb=u.O.extend({h:function(a,c){u.O.call(this,a,c);a.c("timeupdate",u.bind(this,this.Ba));a.M(u.bind(this,this.Ba))}});
t=u.Yb.prototype;t.f={children:{loadProgressBar:{},playProgressBar:{},seekHandle:{}},barName:"playProgressBar",handleName:"seekHandle"};t.pc="timeupdate";t.e=function(){return u.O.prototype.e.call(this,"div",{className:"vjs-progress-holder","aria-label":"video progress bar"})};t.Ba=function(){var a=this.b.Mb?this.b.v.currentTime:this.b.currentTime();this.a.setAttribute("aria-valuenow",u.round(100*this.xb(),2));this.a.setAttribute("aria-valuetext",u.La(a,this.b.duration()))};
t.xb=function(){return this.b.currentTime()/this.b.duration()};t.Pa=function(a){u.O.prototype.Pa.call(this,a);this.b.Mb=f;this.ud=!this.b.paused();this.b.pause()};t.Gb=function(a){a=F(this,a)*this.b.duration();a==this.b.duration()&&(a-=0.1);this.b.currentTime(a)};t.Hb=function(a){u.O.prototype.Hb.call(this,a);this.b.Mb=l;this.ud&&this.b.play()};t.wc=function(){this.b.currentTime(this.b.currentTime()+5)};t.vc=function(){this.b.currentTime(this.b.currentTime()-5)};
u.ab=u.d.extend({h:function(a,c){u.d.call(this,a,c);a.c("progress",u.bind(this,this.update))}});u.ab.prototype.e=function(){return u.d.prototype.e.call(this,"div",{className:"vjs-load-progress",innerHTML:'<span class="vjs-control-text">Loaded: 0%</span>'})};u.ab.prototype.update=function(){this.a.style&&(this.a.style.width=u.round(100*this.b.Ja(),2)+"%")};u.Wb=u.d.extend({h:function(a,c){u.d.call(this,a,c)}});
u.Wb.prototype.e=function(){return u.d.prototype.e.call(this,"div",{className:"vjs-play-progress",innerHTML:'<span class="vjs-control-text">Progress: 0%</span>'})};u.gb=u.fa.extend();u.gb.prototype.defaultValue="00:00";u.gb.prototype.e=function(){return u.fa.prototype.e.call(this,"div",{className:"vjs-seek-handle"})};u.ib=u.d.extend({h:function(a,c){u.d.call(this,a,c);a.g&&(a.g.k&&a.g.k.X===l)&&this.o("vjs-hidden");a.c("loadstart",u.bind(this,function(){a.g.k&&a.g.k.X===l?this.o("vjs-hidden"):this.t("vjs-hidden")}))}});
u.ib.prototype.f={children:{volumeBar:{}}};u.ib.prototype.e=function(){return u.d.prototype.e.call(this,"div",{className:"vjs-volume-control vjs-control"})};u.hb=u.O.extend({h:function(a,c){u.O.call(this,a,c);a.c("volumechange",u.bind(this,this.Ba));a.M(u.bind(this,this.Ba));setTimeout(u.bind(this,this.update),0)}});t=u.hb.prototype;t.Ba=function(){this.a.setAttribute("aria-valuenow",u.round(100*this.b.volume(),2));this.a.setAttribute("aria-valuetext",u.round(100*this.b.volume(),2)+"%")};
t.f={children:{volumeLevel:{},volumeHandle:{}},barName:"volumeLevel",handleName:"volumeHandle"};t.pc="volumechange";t.e=function(){return u.O.prototype.e.call(this,"div",{className:"vjs-volume-bar","aria-label":"volume level"})};t.Gb=function(a){this.b.volume(F(this,a))};t.xb=function(){return this.b.muted()?0:this.b.volume()};t.wc=function(){this.b.volume(this.b.volume()+0.1)};t.vc=function(){this.b.volume(this.b.volume()-0.1)};u.bc=u.d.extend({h:function(a,c){u.d.call(this,a,c)}});
u.bc.prototype.e=function(){return u.d.prototype.e.call(this,"div",{className:"vjs-volume-level",innerHTML:'<span class="vjs-control-text"></span>'})};u.jb=u.fa.extend();u.jb.prototype.defaultValue="00:00";u.jb.prototype.e=function(){return u.fa.prototype.e.call(this,"div",{className:"vjs-volume-handle"})};
u.ea=u.q.extend({h:function(a,c){u.q.call(this,a,c);a.c("volumechange",u.bind(this,this.update));a.g&&(a.g.k&&a.g.k.X===l)&&this.o("vjs-hidden");a.c("loadstart",u.bind(this,function(){a.g.k&&a.g.k.X===l?this.o("vjs-hidden"):this.t("vjs-hidden")}))}});u.ea.prototype.e=function(){return u.q.prototype.e.call(this,"div",{className:"vjs-mute-control vjs-control",innerHTML:'<div><span class="vjs-control-text">Mute</span></div>'})};u.ea.prototype.p=function(){this.b.muted(this.b.muted()?l:f)};
u.ea.prototype.update=function(){var a=this.b.volume(),c=3;0===a||this.b.muted()?c=0:0.33>a?c=1:0.67>a&&(c=2);this.b.muted()?"Unmute"!=this.a.children[0].children[0].innerHTML&&(this.a.children[0].children[0].innerHTML="Unmute"):"Mute"!=this.a.children[0].children[0].innerHTML&&(this.a.children[0].children[0].innerHTML="Mute");for(a=0;4>a;a++)u.t(this.a,"vjs-vol-"+a);u.o(this.a,"vjs-vol-"+c)};
u.na=u.R.extend({h:function(a,c){u.R.call(this,a,c);a.c("volumechange",u.bind(this,this.update));a.g&&(a.g.k&&a.g.k.X===l)&&this.o("vjs-hidden");a.c("loadstart",u.bind(this,function(){a.g.k&&a.g.k.X===l?this.o("vjs-hidden"):this.t("vjs-hidden")}));this.o("vjs-menu-button")}});u.na.prototype.Ka=function(){var a=new u.la(this.b,{Nc:"div"}),c=new u.hb(this.b,u.j.B({td:f},this.f.Hd));a.$(c);return a};u.na.prototype.p=function(){u.ea.prototype.p.call(this);u.R.prototype.p.call(this)};
u.na.prototype.e=function(){return u.q.prototype.e.call(this,"div",{className:"vjs-volume-menu-button vjs-menu-button vjs-control",innerHTML:'<div><span class="vjs-control-text">Mute</span></div>'})};u.na.prototype.update=u.ea.prototype.update;u.cb=u.q.extend({h:function(a,c){u.q.call(this,a,c);(!a.poster()||!a.controls())&&this.C();a.c("play",u.bind(this,this.C))}});
u.cb.prototype.e=function(){var a=u.e("div",{className:"vjs-poster",tabIndex:-1}),c=this.b.poster();c&&("backgroundSize"in a.style?a.style.backgroundImage='url("'+c+'")':a.appendChild(u.e("img",{src:c})));return a};u.cb.prototype.p=function(){this.L().controls()&&this.b.play()};
u.Vb=u.d.extend({h:function(a,c){u.d.call(this,a,c);a.c("canplay",u.bind(this,this.C));a.c("canplaythrough",u.bind(this,this.C));a.c("playing",u.bind(this,this.C));a.c("seeked",u.bind(this,this.C));a.c("seeking",u.bind(this,this.show));a.c("seeked",u.bind(this,this.C));a.c("error",u.bind(this,this.show));a.c("waiting",u.bind(this,this.show))}});u.Vb.prototype.e=function(){return u.d.prototype.e.call(this,"div",{className:"vjs-loading-spinner"})};u.Wa=u.q.extend();
u.Wa.prototype.e=function(){return u.q.prototype.e.call(this,"div",{className:"vjs-big-play-button",innerHTML:"<span></span>","aria-label":"play video"})};u.Wa.prototype.p=function(){this.b.play()};
u.r=u.d.extend({h:function(a,c,d){u.d.call(this,a,c,d);var e,g;g=this;e=this.L();a=function(){if(e.controls()&&!e.Qb()){var a,c;g.c("mousedown",g.p);g.c("touchstart",function(a){a.preventDefault();a.stopPropagation();c=I(this.b)});a=function(a){a.stopPropagation();c&&this.b.sc()};g.c("touchmove",a);g.c("touchleave",a);g.c("touchcancel",a);g.c("touchend",a);var d,n,r;d=0;g.c("touchstart",function(){d=(new Date).getTime();r=f});a=function(){r=l};g.c("touchmove",a);g.c("touchleave",a);g.c("touchcancel",
a);g.c("touchend",function(){r===f&&(n=(new Date).getTime()-d,250>n&&this.i("tap"))});g.c("tap",g.dd)}};c=u.bind(g,g.gd);this.M(a);e.c("controlsenabled",a);e.c("controlsdisabled",c)}});u.r.prototype.gd=function(){this.l("tap");this.l("touchstart");this.l("touchmove");this.l("touchleave");this.l("touchcancel");this.l("touchend");this.l("click");this.l("mousedown")};u.r.prototype.p=function(a){0===a.button&&this.L().controls()&&(this.L().paused()?this.L().play():this.L().pause())};
u.r.prototype.dd=function(){I(this.L(),!I(this.L()))};u.r.prototype.k={X:f,jc:l,Lb:l,Ob:l};u.media={};u.media.Va="play pause paused currentTime setCurrentTime duration buffered volume setVolume muted setMuted width height supportsFullScreen enterFullScreen src load currentSrc preload setPreload autoplay setAutoplay loop setLoop error networkState readyState seeking initialTime startOffsetTime played seekable ended videoTracks audioTracks videoWidth videoHeight textTracks defaultPlaybackRate playbackRate mediaGroup controller controls defaultMuted".split(" ");
function ea(){var a=u.media.Va[i];return function(){throw Error('The "'+a+"\" method is not available on the playback technology's API");}}for(var i=u.media.Va.length-1;0<=i;i--)u.r.prototype[u.media.Va[i]]=ea();
u.n=u.r.extend({h:function(a,c,d){this.k.X=u.n.Mc();this.k.Xc=!u.Cc;this.k.jc=f;u.r.call(this,a,c,d);(c=c.source)&&this.a.currentSrc==c.src?a.i("loadstart"):c&&(this.a.src=c.src);if(u.Ic&&a.options().nativeControlsForTouch!==l){var e,g,h,k;e=this;g=this.L();c=g.controls();e.a.controls=!!c;h=function(){e.a.controls=f};k=function(){e.a.controls=l};g.c("controlsenabled",h);g.c("controlsdisabled",k);c=function(){g.l("controlsenabled",h);g.l("controlsdisabled",k)};e.c("dispose",c);g.c("usingcustomcontrols",
c);g.Qb(f)}a.M(function(){this.F&&(this.f.autoplay&&this.paused())&&(delete this.F.poster,this.play())});for(a=u.n.$a.length-1;0<=a;a--)u.c(this.a,u.n.$a[a],u.bind(this.b,this.Sc));this.Ua()}});t=u.n.prototype;t.D=function(){u.r.prototype.D.call(this)};
t.e=function(){var a=this.b,c=a.F;if(!c||this.k.Xc===l)c?(c.player=j,a.F=j,a.u().removeChild(c),c=c.cloneNode(l)):c=u.e("video",{id:a.id()+"_html5_api",className:"vjs-tech"}),c.player=a,u.yb(c,a.u());for(var d=["autoplay","preload","loop","muted"],e=d.length-1;0<=e;e--){var g=d[e];a.f[g]!==j&&(c[g]=a.f[g])}return c};t.Sc=function(a){this.i(a);a.stopPropagation()};t.play=function(){this.a.play()};t.pause=function(){this.a.pause()};t.paused=function(){return this.a.paused};t.currentTime=function(){return this.a.currentTime};
t.kd=function(a){try{this.a.currentTime=a}catch(c){u.log(c,"Video is not ready. (Video.js)")}};t.duration=function(){return this.a.duration||0};t.buffered=function(){return this.a.buffered};t.volume=function(){return this.a.volume};t.pd=function(a){this.a.volume=a};t.muted=function(){return this.a.muted};t.nd=function(a){this.a.muted=a};t.width=function(){return this.a.offsetWidth};t.height=function(){return this.a.offsetHeight};
t.Ta=function(){return"function"==typeof this.a.webkitEnterFullScreen&&(/Android/.test(u.G)||!/Chrome|Mac OS X 10.5/.test(u.G))?f:l};t.src=function(a){this.a.src=a};t.load=function(){this.a.load()};t.currentSrc=function(){return this.a.currentSrc};t.Qa=function(){return this.a.Qa};t.od=function(a){this.a.Qa=a};t.autoplay=function(){return this.a.autoplay};t.jd=function(a){this.a.autoplay=a};t.controls=function(){return this.a.controls};t.loop=function(){return this.a.loop};
t.md=function(a){this.a.loop=a};t.error=function(){return this.a.error};u.n.isSupported=function(){return!!u.ma.canPlayType};u.n.mb=function(a){try{return!!u.ma.canPlayType(a.type)}catch(c){return""}};u.n.Mc=function(){var a=u.ma.volume;u.ma.volume=a/2+0.1;return a!==u.ma.volume};u.n.$a="loadstart suspend abort error emptied stalled loadedmetadata loadeddata canplay canplaythrough playing waiting seeking seeked ended durationchange timeupdate progress play pause ratechange volumechange".split(" ");
u.Gc&&(document.createElement("video").constructor.prototype.canPlayType=function(a){return a&&-1!=a.toLowerCase().indexOf("video/mp4")?"maybe":""});
u.m=u.r.extend({h:function(a,c,d){u.r.call(this,a,c,d);d=c.source;var e=c.parentEl,g=this.a=u.e("div",{id:a.id()+"_temp_flash"}),h=a.id()+"_flash_api";a=a.f;var k=u.j.B({readyFunction:"videojs.Flash.onReady",eventProxyFunction:"videojs.Flash.onEvent",errorEventProxyFunction:"videojs.Flash.onError",autoplay:a.autoplay,preload:a.Qa,loop:a.loop,muted:a.muted},c.flashVars),q=u.j.B({wmode:"opaque",bgcolor:"#000000"},c.params),n=u.j.B({id:h,name:h,"class":"vjs-tech"},c.attributes);d&&(k.src=encodeURIComponent(u.kc(d.src)));
u.yb(g,e);c.startTime&&this.M(function(){this.load();this.play();this.currentTime(c.startTime)});if(c.iFrameMode===f&&!u.Bc){var r=u.e("iframe",{id:h+"_iframe",name:h+"_iframe",className:"vjs-tech",scrolling:"no",marginWidth:0,marginHeight:0,frameBorder:0});k.readyFunction="ready";k.eventProxyFunction="events";k.errorEventProxyFunction="errors";u.c(r,"load",u.bind(this,function(){var a,d=r.contentWindow;a=r.contentDocument?r.contentDocument:r.contentWindow.document;a.write(u.m.lc(c.swf,k,q,n));d.player=
this.b;d.ready=u.bind(this.b,function(c){var d=this.g;d.a=a.getElementById(c);u.m.pb(d)});d.events=u.bind(this.b,function(a,c){this&&"flash"===this.za&&this.i(c)});d.errors=u.bind(this.b,function(a,c){u.log("Flash Error",c)})}));g.parentNode.replaceChild(r,g)}else u.m.Rc(c.swf,g,k,q,n)}});t=u.m.prototype;t.D=function(){u.r.prototype.D.call(this)};t.play=function(){this.a.vjs_play()};t.pause=function(){this.a.vjs_pause()};
t.src=function(a){a=u.kc(a);this.a.vjs_src(a);if(this.b.autoplay()){var c=this;setTimeout(function(){c.play()},0)}};t.load=function(){this.a.vjs_load()};t.poster=function(){this.a.vjs_getProperty("poster")};t.buffered=function(){return u.sb(0,this.a.vjs_getProperty("buffered"))};t.Ta=s(l);var R=u.m.prototype,S="preload currentTime defaultPlaybackRate playbackRate autoplay loop mediaGroup controller controls volume muted defaultMuted".split(" "),T="error currentSrc networkState readyState seeking initialTime duration startOffsetTime paused played seekable ended videoTracks audioTracks videoWidth videoHeight textTracks".split(" ");
function fa(){var a=S[U],c=a.charAt(0).toUpperCase()+a.slice(1);R["set"+c]=function(c){return this.a.vjs_setProperty(a,c)}}function V(a){R[a]=function(){return this.a.vjs_getProperty(a)}}var U;for(U=0;U<S.length;U++)V(S[U]),fa();for(U=0;U<T.length;U++)V(T[U]);u.m.isSupported=function(){return 10<=u.m.version()[0]};u.m.mb=function(a){if(a.type in u.m.Uc)return"maybe"};u.m.Uc={"video/flv":"FLV","video/x-flv":"FLV","video/mp4":"MP4","video/m4v":"MP4"};
u.m.onReady=function(a){a=u.u(a);var c=a.player||a.parentNode.player,d=c.g;a.player=c;d.a=a;u.m.pb(d)};u.m.pb=function(a){a.u().vjs_getProperty?a.Ua():setTimeout(function(){u.m.pb(a)},50)};u.m.onEvent=function(a,c){u.u(a).player.i(c)};u.m.onError=function(a,c){u.u(a).player.i("error");u.log("Flash Error",c,a)};
u.m.version=function(){var a="0,0,0";try{a=(new window.ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version").replace(/\D+/g,",").match(/^,?(.+),?$/)[1]}catch(c){try{navigator.mimeTypes["application/x-shockwave-flash"].enabledPlugin&&(a=(navigator.plugins["Shockwave Flash 2.0"]||navigator.plugins["Shockwave Flash"]).description.replace(/\D+/g,",").match(/^,?(.+),?$/)[1])}catch(d){}}return a.split(",")};
u.m.Rc=function(a,c,d,e,g){a=u.m.lc(a,d,e,g);a=u.e("div",{innerHTML:a}).childNodes[0];d=c.parentNode;c.parentNode.replaceChild(a,c);var h=d.childNodes[0];setTimeout(function(){h.style.display="block"},1E3)};
u.m.lc=function(a,c,d,e){var g="",h="",k="";c&&u.j.ta(c,function(a,c){g+=a+"="+c+"&amp;"});d=u.j.B({movie:a,flashvars:g,allowScriptAccess:"always",allowNetworking:"all"},d);u.j.ta(d,function(a,c){h+='<param name="'+a+'" value="'+c+'" />'});e=u.j.B({data:a,width:"100%",height:"100%"},e);u.j.ta(e,function(a,c){k+=a+'="'+c+'" '});return'<object type="application/x-shockwave-flash"'+k+">"+h+"</object>"};
u.Hc=u.d.extend({h:function(a,c,d){u.d.call(this,a,c,d);if(!a.f.sources||0===a.f.sources.length){c=0;for(d=a.f.techOrder;c<d.length;c++){var e=u.aa(d[c]),g=window.videojs[e];if(g&&g.isSupported()){J(a,e);break}}}else a.src(a.f.sources)}});function W(a){a.Aa=a.Aa||[];return a.Aa}function X(a,c,d){for(var e=a.Aa,g=0,h=e.length,k,q;g<h;g++)k=e[g],k.id()===c?(k.show(),q=k):d&&(k.K()==d&&0<k.mode())&&k.disable();(c=q?q.K():d?d:l)&&a.i(c+"trackchange")}
u.Y=u.d.extend({h:function(a,c){u.d.call(this,a,c);this.Q=c.id||"vjs_"+c.kind+"_"+c.language+"_"+u.s++;this.uc=c.src;this.Oc=c["default"]||c.dflt;this.rd=c.title;this.Cd=c.srclang;this.Wc=c.label;this.ga=[];this.cc=[];this.ha=this.ia=0;this.b.c("fullscreenchange",u.bind(this,this.Jc))}});t=u.Y.prototype;t.K=p("A");t.src=p("uc");t.tb=p("Oc");t.title=p("rd");t.label=p("Wc");t.readyState=p("ia");t.mode=p("ha");t.Jc=function(){this.a.style.fontSize=this.b.I?140*(screen.width/this.b.width())+"%":""};
t.e=function(){return u.d.prototype.e.call(this,"div",{className:"vjs-"+this.A+" vjs-text-track"})};t.show=function(){Y(this);this.ha=2;u.d.prototype.show.call(this)};t.C=function(){Y(this);this.ha=1;u.d.prototype.C.call(this)};t.disable=function(){2==this.ha&&this.C();this.b.l("timeupdate",u.bind(this,this.update,this.Q));this.b.l("ended",u.bind(this,this.reset,this.Q));this.reset();this.b.V.textTrackDisplay.removeChild(this);this.ha=0};
function Y(a){0===a.ia&&a.load();0===a.ha&&(a.b.c("timeupdate",u.bind(a,a.update,a.Q)),a.b.c("ended",u.bind(a,a.reset,a.Q)),("captions"===a.A||"subtitles"===a.A)&&a.b.V.textTrackDisplay.$(a))}t.load=function(){0===this.ia&&(this.ia=1,u.get(this.uc,u.bind(this,this.ed),u.bind(this,this.Fb)))};t.Fb=function(a){this.error=a;this.ia=3;this.i("error")};
t.ed=function(a){var c,d;a=a.split("\n");for(var e="",g=1,h=a.length;g<h;g++)if(e=u.trim(a[g])){-1==e.indexOf("--\x3e")?(c=e,e=u.trim(a[++g])):c=this.ga.length;c={id:c,index:this.ga.length};d=e.split(" --\x3e ");c.startTime=ga(d[0]);c.ua=ga(d[1]);for(d=[];a[++g]&&(e=u.trim(a[g]));)d.push(e);c.text=d.join("<br/>");this.ga.push(c)}this.ia=2;this.i("loaded")};
function ga(a){var c=a.split(":");a=0;var d,e,g;3==c.length?(d=c[0],e=c[1],c=c[2]):(d=0,e=c[0],c=c[1]);c=c.split(/\s+/);c=c.splice(0,1)[0];c=c.split(/\.|,/);g=parseFloat(c[1]);c=c[0];a+=3600*parseFloat(d);a+=60*parseFloat(e);a+=parseFloat(c);g&&(a+=g/1E3);return a}
t.update=function(){if(0<this.ga.length){var a=this.b.currentTime();if(this.Kb===b||a<this.Kb||this.Ma<=a){var c=this.ga,d=this.b.duration(),e=0,g=l,h=[],k,q,n,r;a>=this.Ma||this.Ma===b?r=this.vb!==b?this.vb:0:(g=f,r=this.Cb!==b?this.Cb:c.length-1);for(;;){n=c[r];if(n.ua<=a)e=Math.max(e,n.ua),n.Ia&&(n.Ia=l);else if(a<n.startTime){if(d=Math.min(d,n.startTime),n.Ia&&(n.Ia=l),!g)break}else g?(h.splice(0,0,n),q===b&&(q=r),k=r):(h.push(n),k===b&&(k=r),q=r),d=Math.min(d,n.ua),e=Math.max(e,n.startTime),
n.Ia=f;if(g)if(0===r)break;else r--;else if(r===c.length-1)break;else r++}this.cc=h;this.Ma=d;this.Kb=e;this.vb=k;this.Cb=q;a=this.cc;c="";d=0;for(e=a.length;d<e;d++)c+='<span class="vjs-tt-cue">'+a[d].text+"</span>";this.a.innerHTML=c;this.i("cuechange")}}};t.reset=function(){this.Ma=0;this.Kb=this.b.duration();this.Cb=this.vb=0};u.Tb=u.Y.extend();u.Tb.prototype.A="captions";u.Zb=u.Y.extend();u.Zb.prototype.A="subtitles";u.Ub=u.Y.extend();u.Ub.prototype.A="chapters";
u.$b=u.d.extend({h:function(a,c,d){u.d.call(this,a,c,d);if(a.f.tracks&&0<a.f.tracks.length){c=this.b;a=a.f.tracks;var e;for(d=0;d<a.length;d++){e=a[d];var g=c,h=e.kind,k=e.label,q=e.language,n=e;e=g.Aa=g.Aa||[];n=n||{};n.kind=h;n.label=k;n.language=q;h=u.aa(h||"subtitles");g=new window.videojs[h+"Track"](g,n);e.push(g)}}}});u.$b.prototype.e=function(){return u.d.prototype.e.call(this,"div",{className:"vjs-text-track-display"})};
u.Z=u.N.extend({h:function(a,c){var d=this.da=c.track;c.label=d.label();c.selected=d.tb();u.N.call(this,a,c);this.b.c(d.K()+"trackchange",u.bind(this,this.update))}});u.Z.prototype.p=function(){u.N.prototype.p.call(this);X(this.b,this.da.Q,this.da.K())};u.Z.prototype.update=function(){this.selected(2==this.da.mode())};u.bb=u.Z.extend({h:function(a,c){c.track={K:function(){return c.kind},L:a,label:function(){return c.kind+" off"},tb:s(l),mode:s(l)};u.Z.call(this,a,c);this.selected(f)}});
u.bb.prototype.p=function(){u.Z.prototype.p.call(this);X(this.b,this.da.Q,this.da.K())};u.bb.prototype.update=function(){for(var a=W(this.b),c=0,d=a.length,e,g=f;c<d;c++)e=a[c],e.K()==this.da.K()&&2==e.mode()&&(g=l);this.selected(g)};u.S=u.R.extend({h:function(a,c){u.R.call(this,a,c);1>=this.J.length&&this.C()}});u.S.prototype.sa=function(){var a=[],c;a.push(new u.bb(this.b,{kind:this.A}));for(var d=0;d<W(this.b).length;d++)c=W(this.b)[d],c.K()===this.A&&a.push(new u.Z(this.b,{track:c}));return a};
u.Da=u.S.extend({h:function(a,c,d){u.S.call(this,a,c,d);this.a.setAttribute("aria-label","Captions Menu")}});u.Da.prototype.A="captions";u.Da.prototype.pa="Captions";u.Da.prototype.className="vjs-captions-button";u.Ha=u.S.extend({h:function(a,c,d){u.S.call(this,a,c,d);this.a.setAttribute("aria-label","Subtitles Menu")}});u.Ha.prototype.A="subtitles";u.Ha.prototype.pa="Subtitles";u.Ha.prototype.className="vjs-subtitles-button";
u.Ea=u.S.extend({h:function(a,c,d){u.S.call(this,a,c,d);this.a.setAttribute("aria-label","Chapters Menu")}});t=u.Ea.prototype;t.A="chapters";t.pa="Chapters";t.className="vjs-chapters-button";t.sa=function(){for(var a=[],c,d=0;d<W(this.b).length;d++)c=W(this.b)[d],c.K()===this.A&&a.push(new u.Z(this.b,{track:c}));return a};
t.Ka=function(){for(var a=W(this.b),c=0,d=a.length,e,g,h=this.J=[];c<d;c++)if(e=a[c],e.K()==this.A&&e.tb()){if(2>e.readyState()){this.Ad=e;e.c("loaded",u.bind(this,this.Ka));return}g=e;break}a=this.va=new u.la(this.b);a.a.appendChild(u.e("li",{className:"vjs-menu-title",innerHTML:u.aa(this.A),qd:-1}));if(g){e=g.ga;for(var k,c=0,d=e.length;c<d;c++)k=e[c],k=new u.Xa(this.b,{track:g,cue:k}),h.push(k),a.$(k)}0<this.J.length&&this.show();return a};
u.Xa=u.N.extend({h:function(a,c){var d=this.da=c.track,e=this.cue=c.cue,g=a.currentTime();c.label=e.text;c.selected=e.startTime<=g&&g<e.ua;u.N.call(this,a,c);d.c("cuechange",u.bind(this,this.update))}});u.Xa.prototype.p=function(){u.N.prototype.p.call(this);this.b.currentTime(this.cue.startTime);this.update(this.cue.startTime)};u.Xa.prototype.update=function(){var a=this.cue,c=this.b.currentTime();this.selected(a.startTime<=c&&c<a.ua)};
u.j.B(u.Fa.prototype.f.children,{subtitlesButton:{},captionsButton:{},chaptersButton:{}});
if("undefined"!==typeof window.JSON&&"function"===window.JSON.parse)u.JSON=window.JSON;else{u.JSON={};var Z=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g;u.JSON.parse=function(a,c){function d(a,e){var k,q,n=a[e];if(n&&"object"===typeof n)for(k in n)Object.prototype.hasOwnProperty.call(n,k)&&(q=d(n,k),q!==b?n[k]=q:delete n[k]);return c.call(a,e,n)}var e;a=String(a);Z.lastIndex=0;Z.test(a)&&(a=a.replace(Z,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)}));
if(/^[\],:{}\s]*$/.test(a.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,"")))return e=eval("("+a+")"),"function"===typeof c?d({"":e},""):e;throw new SyntaxError("JSON.parse(): invalid or malformed JSON data");}}
u.dc=function(){var a,c,d=document.getElementsByTagName("video");if(d&&0<d.length)for(var e=0,g=d.length;e<g;e++)if((c=d[e])&&c.getAttribute)c.player===b&&(a=c.getAttribute("data-setup"),a!==j&&(a=u.JSON.parse(a||"{}"),v(c,a)));else{u.kb();break}else u.vd||u.kb()};u.kb=function(){setTimeout(u.dc,1)};u.U(window,"load",function(){u.vd=f});u.kb();u.fd=function(a,c){u.w.prototype[a]=c};var ha=this;ha.wd=f;function $(a,c){var d=a.split("."),e=ha;!(d[0]in e)&&e.execScript&&e.execScript("var "+d[0]);for(var g;d.length&&(g=d.shift());)!d.length&&c!==b?e[g]=c:e=e[g]?e[g]:e[g]={}};$("videojs",u);$("_V_",u);$("videojs.options",u.options);$("videojs.players",u.wa);$("videojs.cache",u.qa);$("videojs.Component",u.d);u.d.prototype.player=u.d.prototype.L;u.d.prototype.dispose=u.d.prototype.D;u.d.prototype.createEl=u.d.prototype.e;u.d.prototype.el=u.d.prototype.u;u.d.prototype.addChild=u.d.prototype.$;u.d.prototype.children=u.d.prototype.children;u.d.prototype.on=u.d.prototype.c;u.d.prototype.off=u.d.prototype.l;u.d.prototype.one=u.d.prototype.U;u.d.prototype.trigger=u.d.prototype.i;
u.d.prototype.triggerReady=u.d.prototype.Ua;u.d.prototype.show=u.d.prototype.show;u.d.prototype.hide=u.d.prototype.C;u.d.prototype.width=u.d.prototype.width;u.d.prototype.height=u.d.prototype.height;u.d.prototype.dimensions=u.d.prototype.Pc;u.d.prototype.ready=u.d.prototype.M;$("videojs.Player",u.w);u.w.prototype.dispose=u.w.prototype.D;u.w.prototype.requestFullScreen=u.w.prototype.xa;u.w.prototype.cancelFullScreen=u.w.prototype.ob;u.w.prototype.bufferedPercent=u.w.prototype.Ja;
u.w.prototype.usingNativeControls=u.w.prototype.Qb;$("videojs.MediaLoader",u.Hc);$("videojs.TextTrackDisplay",u.$b);$("videojs.ControlBar",u.Fa);$("videojs.Button",u.q);$("videojs.PlayToggle",u.Xb);$("videojs.FullscreenToggle",u.Ga);$("videojs.BigPlayButton",u.Wa);$("videojs.LoadingSpinner",u.Vb);$("videojs.CurrentTimeDisplay",u.Ya);$("videojs.DurationDisplay",u.Za);$("videojs.TimeDivider",u.ac);$("videojs.RemainingTimeDisplay",u.fb);$("videojs.Slider",u.O);$("videojs.ProgressControl",u.eb);
$("videojs.SeekBar",u.Yb);$("videojs.LoadProgressBar",u.ab);$("videojs.PlayProgressBar",u.Wb);$("videojs.SeekHandle",u.gb);$("videojs.VolumeControl",u.ib);$("videojs.VolumeBar",u.hb);$("videojs.VolumeLevel",u.bc);$("videojs.VolumeMenuButton",u.na);$("videojs.VolumeHandle",u.jb);$("videojs.MuteToggle",u.ea);$("videojs.PosterImage",u.cb);$("videojs.Menu",u.la);$("videojs.MenuItem",u.N);$("videojs.MenuButton",u.R);u.R.prototype.createItems=u.R.prototype.sa;u.S.prototype.createItems=u.S.prototype.sa;
u.Ea.prototype.createItems=u.Ea.prototype.sa;$("videojs.SubtitlesButton",u.Ha);$("videojs.CaptionsButton",u.Da);$("videojs.ChaptersButton",u.Ea);$("videojs.MediaTechController",u.r);u.r.prototype.features=u.r.prototype.k;u.r.prototype.k.volumeControl=u.r.prototype.k.X;u.r.prototype.k.fullscreenResize=u.r.prototype.k.jc;u.r.prototype.k.progressEvents=u.r.prototype.k.Lb;u.r.prototype.k.timeupdateEvents=u.r.prototype.k.Ob;$("videojs.Html5",u.n);u.n.Events=u.n.$a;u.n.isSupported=u.n.isSupported;
u.n.canPlaySource=u.n.mb;u.n.prototype.setCurrentTime=u.n.prototype.kd;u.n.prototype.setVolume=u.n.prototype.pd;u.n.prototype.setMuted=u.n.prototype.nd;u.n.prototype.setPreload=u.n.prototype.od;u.n.prototype.setAutoplay=u.n.prototype.jd;u.n.prototype.setLoop=u.n.prototype.md;$("videojs.Flash",u.m);u.m.isSupported=u.m.isSupported;u.m.canPlaySource=u.m.mb;u.m.onReady=u.m.onReady;$("videojs.TextTrack",u.Y);u.Y.prototype.label=u.Y.prototype.label;$("videojs.CaptionsTrack",u.Tb);
$("videojs.SubtitlesTrack",u.Zb);$("videojs.ChaptersTrack",u.Ub);$("videojs.autoSetup",u.dc);$("videojs.plugin",u.fd);$("videojs.createTimeRange",u.sb);})();//@ sourceMappingURL=video.js.map
